# -*- coding: utf-8 -*-
"""PreAttack_labels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fnv4SAIoSAElgo5yZz42P0W_bQzZ9MW-
"""

'''

arr = A list of annotations
a_w : size of attack window for which we consider those frames as attack, default=1
pa_w : size of window that will decide how many preceeding frames will be changed to pre-attack behavior, default=30
pa_l : label for pre-attack behavior, default=4

'''

def change_labels(arr, a_w=1, pa_w=30, pa_l=4):
    i = 0
    while i < len(arr) - a_w:
        if arr[i:i+a_w] == a_w*[0]:
            if i >= pa_w:
                arr[i-pa_w:i] = pa_w*[pa_l]
            else:
                arr[:i] = [pa_l] * i
            i += 1
        else:
            i += 1
    return arr